#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Chef Enhancements
cookbook 'chef-solo-search', git: 'git://github.com/edelight/chef-solo-search.git'

# Base
cookbook 'hostname', git: 'https://github.com/nickola/chef-hostname.git'
cookbook 'apt'
cookbook 'fail2ban'
cookbook 'htop'
cookbook 'logrotate'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'postfix'
cookbook 'sudo'
cookbook 'sysctl'
cookbook 'ufw'
cookbook 'unattended-upgrades', git: 'git://github.com/firstbanco/chef-unattended-upgrades.git'
cookbook 'user', git: 'git://github.com/fnichol/chef-user.git'
cookbook 'xml'
cookbook 'zsh'
cookbook 'platform_packages'

cookbook 'newrelic', git: 'https://github.com/heavywater/chef-newrelic.git'

# Nginx
cookbook 'nginx'

# Apache
cookbook 'apache2'

# Puma App
cookbook 'ruby_install', git: 'https://github.com/rosstimson/chef-ruby_install.git'

# Calagator
cookbook 'sqlite'
# cookbook 'hipsnip-solr', git: 'https://github.com/hipsnip-cookbooks/solr.git'

# Temporarily use my fork of hipsnip-solr, pending:
# - https://github.com/hipsnip-cookbooks/solr/pull/5
# - https://github.com/hipsnip-cookbooks/solr/pull/6
cookbook 'hipsnip-solr', git: 'https://github.com/reidab/solr.git', ref: 'both_fixes'

# Etherpad
cookbook 'etherpad-lite', git: 'https://github.com/OpenWatch/etherpad-lite-cookbook.git'
cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql.git'
cookbook 'nodejs'

# ZNC Server
cookbook 'znc', git: 'https://github.com/reidab/znc.git'

# IRC Server
cookbook 'ngircd', git: 'https://github.com/reidab/cookbook-ngircd.git'
cookbook 'atheme-services', git: 'https://github.com/reidab/chef-atheme-services.git'

# Wordpress
cookbook 'mysql'
cookbook 'database'
