#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'fail2ban'
cookbook 'htop'
cookbook 'logrotate'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'postfix'
cookbook 'rsync'
cookbook 'sudo'
cookbook 'ufw'
cookbook 'unattended-upgrades', git: 'git://github.com/firstbanco/chef-unattended-upgrades.git'
cookbook 'vim'
cookbook 'zsh'
