#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'apt'
cookbook 'postfix'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'vim'
cookbook 'zsh'
cookbook 'rsync'
cookbook 'htop'
